version: '3.8'

services:
  unstructured:
    image: downloads.unstructured.io/unstructured-io/unstructured:latest
    container_name: unstructured
    ports:
      - 9000:9000  # Adjust the port as needed
    stdin_open: true
    tty: true
    command: bash
